### ISSUE TITLE
모듈 관리자가 시험응시현황을 볼 수 없는 문제

### ISSUE THREAD

**Issue by hyunixxx1230** [YJSoft/rx-module-exam#43]
최고 관리자는 시험응시현황을 볼 수 있으나
모듈 관리자는 권한이 없습니다.

모듈 관리자도 취지상 확인이 가능해야 하지 않을까 싶습니다.

**Comment by cydemo** [comment]
모듈관리자의 응시 현황 보기의 경우
module.xml 에 퍼미션 속성을 넣어주면 되긴 하는데
`<action name="dispExamAdminResultList" type="view" permission="manager" />`

문제는 그렇게 해도 수정(dispExamAdminResultUpdate)으로 들어가면 admin 모듈로 넘어가기 때문에 결국 모듈관리자는 시험응시현황 수정을 할 수 없게 됩니다.
아마도 이와 비슷하게 view와 controller에 대한 permission 이슈가 더 있을 수도 있겠다는 생각이 듭니다.

**Comment by YJSoft** [comment]
db735edc49423f1ea220d53237f6ca3ab8d74f1a ec5ce984023891fb294b02f2b6ddd64b73dd5bdb
